version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      # Install virtualenv if not already installed
      - pip install virtualenv
      # Create a new virtual environment named "venv"
      - virtualenv venv
      # Upgrade pip inside the virtual environment
      - venv/bin/pip install --upgrade pip
      # Install AWS SDK for Python (boto3) within the virtual environment
      - venv/bin/pip install boto3

  build:
    commands:
      - cd aws
      # Activate the virtual environment and execute the Python script directly
      - venv/bin/python instance.py
      # Your other build commands here

  post_build:
    commands:
      # Deactivate the virtual environment after the build is complete (Not necessary for CodeBuild)
      - deactivate
      # Any post-build commands here
