version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      # Install virtualenv if not already installed
      - pip install virtualenv
      # Create a new virtual environment named "venv"
      - virtualenv venv
      # Activate the virtual environment
      - source venv/bin/activate
      # Upgrade pip inside the virtual environment
      - pip install --upgrade pip
      # Install AWS SDK for Python (boto3) within the virtual environment
      - pip install boto3

  build:
    commands:
      - cd aws
      # The virtual environment is already activated, so you can directly run the Python script
      - python instance.py
      # Your other build commands here

  post_build:
    commands:
      # Deactivate the virtual environment after the build is complete
      - deactivate
      # Any post-build commands here
