version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - python -m venv venv      
      - source venv/bin/activate
      - pip install boto3  # Install AWS SDK for Python
      - pip install --upgrade pip
      

  build:
    commands:
      - cd aws
      - python instance.py

# Use the build image with Python 3.8
environment:
  image: aws/codebuild/standard:5.0
